### ISSUE TITLE
Headers after Body

### ISSUE THREAD

**Issue by badu** [fragmenta/view#3]
In render.go lines 259 - 260, you are writing the Headers after you have written the Body. If you check your Headers in the browser, you will see they do not contain the written values.
_, err := io.WriteString(r.writer, r.context["content"].(string))
r.writer.Header().Set("Content-Type", r.format+"; charset=utf-8")
should be : 
r.writer.Header().Set("Content-Type", r.format+"; charset=utf-8")
_, err := io.WriteString(r.writer, r.context["content"].(string))

**Comment by kennygrant** [comment]
Thanks, I'll look into and fix this.
